[pytest]
testpaths = tests
addopts = -v --tb=short

log_cli = true
log_cli_level = INFO

filterwarnings =
    ignore::DeprecationWarning

markers =
    smoke: критичные минимальные тесты
    api: happy path тесты
    negative: негативные сценарии
    regression: регрессионные тесты
    xfail: ожидаемые падения (баги на стороне API)
